### ISSUE TITLE
Could not load 'plugins/AudioConnect.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by Patrick15a** [DeadmanDungeons/AudioConnect#1]
Where i found the DeadmanPlugin?

Your *plugin.yml*:

```
name: AudioConnect
main: com.deadmandungeons.audioconnect.AudioConnect
version: 1.2.5
author: Weasel_Squeezer
website: https://minecraftaudio.com

depend: [DeadmanPlugin, WorldGuard]

...
```

Exception:
```
org.bukkit.plugin.UnknownDependencyException: DeadmanPlugin
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [spigot.jar:git-Spigot-54ec0b8-7b044de]
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:301) [spigot.jar:git-Spigot-54ec0b8-7b044de]
at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:204) [spigot.jar:git-Spigot-54ec0b8-7b044de]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-54ec0b8-7b044de]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by JonMcPherson** [comment]
Oh wow...
DeadmanPlugin is included in the jar.  I just forgot to remove that dependency declaration.

The spigot resource has been updated with a new version that fixes this from commit https://github.com/DeadmanDungeons/AudioConnect/commit/dd5b04b664dd1aae9a8f32e1984531b6c068fdac
